# Read the documentation before extending the defaults:
# https://docs.searxng.org/admin/settings/

use_default_settings: true

server:
  secret_key: "Zhv2JHFEMNAz8mAArdRv9ByCi6KcLFs"
  image_proxy: true
